/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mernokinformatikus_prog3.vallalatiranyitas;

/**
 *
 * @author Zsolti
 */
public class FooldalFrame extends javax.swing.JFrame {

    private CoreFunctions CF = new CoreFunctions();
    /**
     * Creates new form FooldalFrame
     */
    public FooldalFrame() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFooldal = new javax.swing.JPanel();
        jButtonBezar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaKiir = new javax.swing.JTextArea();
        jButtonKiir = new javax.swing.JButton();
        jButtonTorol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bejelentkezés");
        setBackground(new java.awt.Color(0, 102, 102));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setName("frameFooldal"); // NOI18N

        jPanelFooldal.setBackground(new java.awt.Color(0, 63, 96));
        jPanelFooldal.setName("fooldalPanel"); // NOI18N

        javax.swing.GroupLayout jPanelFooldalLayout = new javax.swing.GroupLayout(jPanelFooldal);
        jPanelFooldal.setLayout(jPanelFooldalLayout);
        jPanelFooldalLayout.setHorizontalGroup(
            jPanelFooldalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jPanelFooldalLayout.setVerticalGroup(
            jPanelFooldalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jButtonBezar.setBackground(new java.awt.Color(60, 145, 183));
        jButtonBezar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBezar.setText("Bezár");
        jButtonBezar.setActionCommand("JButtonBezar");
        jButtonBezar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBezarActionPerformed(evt);
            }
        });

        jTextAreaKiir.setColumns(20);
        jTextAreaKiir.setRows(5);
        jScrollPane2.setViewportView(jTextAreaKiir);

        jButtonKiir.setBackground(new java.awt.Color(60, 145, 183));
        jButtonKiir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonKiir.setText("Kiír");
        jButtonKiir.setActionCommand("");
        jButtonKiir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonKiir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKiirActionPerformed(evt);
            }
        });

        jButtonTorol.setBackground(new java.awt.Color(51, 204, 255));
        jButtonTorol.setText("Törlés");
        jButtonTorol.setActionCommand("");
        jButtonTorol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTorol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTorolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelFooldal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBezar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButtonKiir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTorol, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(457, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(200, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(233, 233, 233)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFooldal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBezar)
                .addGap(190, 190, 190)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKiir)
                    .addComponent(jButtonTorol))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(287, Short.MAX_VALUE)))
        );

        jButtonKiir.getAccessibleContext().setAccessibleName("Kiír");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBezarActionPerformed
        CF.bezaras();
    }//GEN-LAST:event_jButtonBezarActionPerformed

    private void jButtonKiirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKiirActionPerformed
        jTextAreaKiir.setText("Szevasz!");
    }//GEN-LAST:event_jButtonKiirActionPerformed

    private void jButtonTorolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTorolActionPerformed
        jTextAreaKiir.setText(null);
    }//GEN-LAST:event_jButtonTorolActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBezar;
    private javax.swing.JButton jButtonKiir;
    private javax.swing.JButton jButtonTorol;
    private javax.swing.JPanel jPanelFooldal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaKiir;
    // End of variables declaration//GEN-END:variables
}